version: '3.5'
services:
  build:
    image: golang:1.9.2
    environment:
      - GOOS=linux
      - GOARCH=amd64
      - CGO_ENABLED=0
    volumes:
      - .:/go
  test:
    build: .
    image: drone_webhook
